backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
      